[package]
name = "git-branch-history"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
git2 = "0.16.1"
lazy_static = "1.4.0"
regex = "1.7.1"
